FROM debian:latest

RUN apt update -y && apt upgrade -y && apt install curl -y && apt install python3 python3.11-venv -y

WORKDIR /backend

COPY . .

COPY ./script.sh /

RUN chmod +x /script.sh

CMD [ "/script.sh" ]